[package]
name = "frost-snake-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frost-snake-lib = { path = "../lib" }
fixed = { version = "1", features = ["std"] }
eyre = "0.6.8"
